//! Build script for `libaipm-engine-spec`.
//!
//! Pipeline:
//!   1. emit `cargo:rerun-if-changed` for the inputs.
//!   2. validate `data/engine-api-schema.json` against
//!      `schemas/engine-api.schema.json` (auto-detects 2020-12 dialect).
//!   3. deserialize the validated data into [`types::EngineApiSchemaFile`].
//!   4. assert the data file's `meta_schema_version` matches
//!      [`types::META_SCHEMA_VERSION`].
//!   5. emit `OUT_DIR/engine_data.rs` containing typed const tables.
//!
//! Today the codegen step emits the generated `Engine` enum and
//! `EngineSet` bitflags. Later features extend the generated module
//! with `ENGINES`, `VALID_TOOLS`, `TOOL_COMPATIBILITY`,
//! `HOOK_EVENTS_BY_ENGINE`, `paths`, and `constraints`.
//!
//! `println!` is denied workspace-wide so cargo directives are
//! emitted via `writeln!(io::stdout(), …)` instead.

use std::io::Write;

use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;

#[path = "src/types.rs"]
mod types;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    emit_rerun_directives()?;

    let parsed = load_and_validate()?;

    let tokens = generate_engine_module(&parsed);
    let formatted = prettyplease::unparse(&syn::parse2(tokens)?);

    let out_dir = std::env::var("OUT_DIR")?;
    let dest = std::path::Path::new(&out_dir).join("engine_data.rs");
    std::fs::write(dest, formatted)?;

    Ok(())
}

fn emit_rerun_directives() -> Result<(), std::io::Error> {
    let stdout = std::io::stdout();
    let mut handle = stdout.lock();
    for line in [
        "cargo:rerun-if-changed=data/engine-api-schema.json",
        "cargo:rerun-if-changed=../../schemas/engine-api.schema.json",
        "cargo:rerun-if-changed=src/types.rs",
        "cargo:rerun-if-changed=build.rs",
    ] {
        writeln!(handle, "{line}")?;
    }
    Ok(())
}

fn load_and_validate() -> Result<types::EngineApiSchemaFile, Box<dyn std::error::Error>> {
    let meta_schema_text = std::fs::read_to_string("../../schemas/engine-api.schema.json")?;
    let data_text = std::fs::read_to_string("data/engine-api-schema.json")?;

    let meta_schema: serde_json::Value = serde_json::from_str(&meta_schema_text)?;
    let data: serde_json::Value = serde_json::from_str(&data_text)?;

    let validator = jsonschema::validator_for(&meta_schema)?;
    if let Err(e) = validator.validate(&data) {
        return Err(format!(
            "data/engine-api-schema.json fails meta-schema validation: {e}\n\
             If the meta-schema needs updating, edit src/types.rs and re-run \
             `cargo run -p libaipm-engine-spec --bin export-schema`."
        )
        .into());
    }

    let parsed: types::EngineApiSchemaFile = serde_json::from_value(data)?;

    if parsed.meta_schema_version != types::META_SCHEMA_VERSION {
        return Err(format!(
            "meta_schema_version mismatch: data file says {data_v} but src/types.rs says {types_v}",
            data_v = parsed.meta_schema_version,
            types_v = types::META_SCHEMA_VERSION,
        )
        .into());
    }

    Ok(parsed)
}

fn generate_engine_module(parsed: &types::EngineApiSchemaFile) -> TokenStream {
    let variants: Vec<Ident> = parsed
        .engines
        .iter()
        .map(|e| Ident::new(&to_pascal_case(&e.name), Span::call_site()))
        .collect();
    let names: Vec<&str> = parsed.engines.iter().map(|e| e.name.as_str()).collect();
    let flag_names: Vec<Ident> = parsed
        .engines
        .iter()
        .map(|e| Ident::new(&to_screaming_snake(&e.name), Span::call_site()))
        .collect();
    let bit_values: Vec<u32> = parsed
        .engines
        .iter()
        .enumerate()
        .map(|(i, _)| 1u32 << u32::try_from(i).unwrap_or(0))
        .collect();

    quote! {
        // @generated by build.rs from data/engine-api-schema.json — do not edit.

        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum Engine {
            #( #variants, )*
        }

        impl Engine {
            pub const ALL: &'static [Self] = &[ #( Self::#variants ),* ];

            #[must_use]
            pub const fn name(self) -> &'static str {
                match self {
                    #( Self::#variants => #names, )*
                }
            }

            #[must_use]
            pub fn from_name(name: &str) -> Option<Self> {
                match name {
                    #( #names => Some(Self::#variants), )*
                    _ => None,
                }
            }
        }

        bitflags::bitflags! {
            #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
            pub struct EngineSet: u32 {
                #( const #flag_names = #bit_values; )*
                const ALL = #( Self::#flag_names.bits() )|*;
            }
        }
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('-')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            chars.next().map_or_else(String::new, |first| {
                first.to_uppercase().chain(chars).collect::<String>()
            })
        })
        .collect()
}

fn to_screaming_snake(s: &str) -> String {
    s.replace('-', "_").to_uppercase()
}
