//! Lockfile management for `aipm.lock`.
//!
//! Handles reading, writing, and validating the lockfile that records
//! exact resolved dependency versions with integrity hashes.

pub mod error;
pub mod reconcile;
pub mod types;

use std::path::Path;

use error::Error;
use types::{Lockfile, LOCKFILE_VERSION};

/// Header comment written at the top of every `aipm.lock` file.
const LOCKFILE_HEADER: &str = "\
# This file is automatically generated by aipm.\n\
# It records the exact dependency tree for deterministic installs.\n\
# See https://github.com/TheLarkInn/aipm for details.\n\n";

/// Read and parse an `aipm.lock` file from the given path.
///
/// # Errors
///
/// Returns [`Error::Io`] if the file cannot be read.
/// Returns [`Error::Parse`] if the TOML is invalid.
/// Returns [`Error::UnsupportedVersion`] if the lockfile version is not supported.
pub fn read(path: &Path) -> Result<Lockfile, Error> {
    let content = std::fs::read_to_string(path)
        .map_err(|source| Error::Io { path: path.to_path_buf(), source })?;

    let lockfile: Lockfile =
        toml::from_str(&content).map_err(|e| Error::Parse { reason: e.to_string() })?;

    if lockfile.metadata.lockfile_version != LOCKFILE_VERSION {
        return Err(Error::UnsupportedVersion {
            version: lockfile.metadata.lockfile_version,
            expected: LOCKFILE_VERSION,
        });
    }

    Ok(lockfile)
}

/// Serialize and write a lockfile to the given path.
///
/// The file is written with a header comment explaining its purpose.
///
/// # Errors
///
/// Returns [`Error::Io`] if the file cannot be written.
/// Returns [`Error::Parse`] if serialization fails (should not happen for valid data).
pub fn write(path: &Path, lockfile: &Lockfile) -> Result<(), Error> {
    let body = toml::to_string(lockfile).map_err(|e| Error::Parse { reason: e.to_string() })?;

    let content = format!("{LOCKFILE_HEADER}{body}");

    // Ensure parent directory exists
    if let Some(parent) = path.parent() {
        if !parent.exists() {
            std::fs::create_dir_all(parent)
                .map_err(|source| Error::Io { path: parent.to_path_buf(), source })?;
        }
    }

    std::fs::write(path, content.as_bytes())
        .map_err(|source| Error::Io { path: path.to_path_buf(), source })
}

/// Validate that a lockfile matches a set of manifest dependency names.
///
/// Used for `--locked` mode: fails if there are dependencies in the manifest
/// that are not in the lockfile, or lockfile packages not in the manifest
/// (excluding transitive dependencies — this checks only direct deps).
///
/// `manifest_deps` should be the set of direct dependency names from the manifest.
///
/// # Errors
///
/// Returns [`Error::Drift`] describing any mismatches found.
pub fn validate_matches_manifest(
    lockfile: &Lockfile,
    manifest_deps: &std::collections::BTreeSet<String>,
) -> Result<(), Error> {
    let locked_names: std::collections::BTreeSet<String> =
        lockfile.packages.iter().map(|p| p.name.clone()).collect();

    let mut issues = Vec::new();

    // Deps in manifest but not in lockfile
    for dep in manifest_deps {
        if !locked_names.contains(dep) {
            issues.push(format!("dependency '{dep}' is in manifest but not in lockfile"));
        }
    }

    // Direct deps in lockfile but not in manifest (could be transitive, so this
    // is a simpler check — we just verify manifest deps are present)

    if issues.is_empty() {
        Ok(())
    } else {
        Err(Error::Drift { reason: issues.join("; ") })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use types::{Metadata, Package};

    fn sample_lockfile() -> Lockfile {
        Lockfile {
            metadata: Metadata { lockfile_version: 1, generated_by: "aipm 0.10.0".to_string() },
            packages: vec![
                Package {
                    name: "code-review".to_string(),
                    version: "1.2.0".to_string(),
                    source: "git+https://github.com/org/aipm-registry.git".to_string(),
                    checksum: "sha512-abc123".to_string(),
                    dependencies: vec!["lint-skill ^1.0".to_string()],
                },
                Package {
                    name: "lint-skill".to_string(),
                    version: "1.5.0".to_string(),
                    source: "git+https://github.com/org/aipm-registry.git".to_string(),
                    checksum: "sha512-789ghi".to_string(),
                    dependencies: vec![],
                },
            ],
        }
    }

    #[test]
    fn write_and_read_round_trip() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("aipm.lock");

        let lf = sample_lockfile();
        write(&path, &lf).unwrap();
        let read_back = read(&path).unwrap();

        assert_eq!(lf, read_back);
    }

    #[test]
    fn written_file_contains_header() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("aipm.lock");

        write(&path, &sample_lockfile()).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();

        assert!(content.starts_with("# This file is automatically generated by aipm."));
        assert!(content.contains("# See https://github.com/TheLarkInn/aipm"));
    }

    #[test]
    fn read_empty_lockfile() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("aipm.lock");

        let lf = Lockfile::new("aipm 0.10.0".to_string());
        write(&path, &lf).unwrap();
        let read_back = read(&path).unwrap();

        assert!(read_back.packages.is_empty());
        assert_eq!(read_back.metadata.lockfile_version, 1);
    }

    #[test]
    fn read_nonexistent_file_errors() {
        let result = read(Path::new("/nonexistent/aipm.lock"));
        assert!(result.is_err());
    }

    #[test]
    fn read_invalid_toml_errors() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("aipm.lock");
        std::fs::write(&path, "this is not valid TOML {{{").unwrap();

        let result = read(&path);
        assert!(result.is_err());
    }

    #[test]
    fn read_unsupported_version_errors() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("aipm.lock");
        let content = r#"
[metadata]
lockfile_version = 99
generated_by = "future-aipm"
"#;
        std::fs::write(&path, content).unwrap();

        let result = read(&path);
        assert!(result.is_err());
        let err_msg = format!("{}", result.as_ref().err().unwrap());
        assert!(err_msg.contains("99"));
    }

    #[test]
    fn write_creates_parent_directories() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("deep").join("nested").join("aipm.lock");

        let lf = Lockfile::new("aipm 0.10.0".to_string());
        write(&path, &lf).unwrap();
        assert!(path.exists());
    }

    #[test]
    fn validate_matches_manifest_all_present() {
        let lf = sample_lockfile();
        let deps: std::collections::BTreeSet<String> =
            ["code-review", "lint-skill"].iter().map(|s| (*s).to_string()).collect();

        assert!(validate_matches_manifest(&lf, &deps).is_ok());
    }

    #[test]
    fn validate_matches_manifest_missing_dep() {
        let lf = sample_lockfile();
        let deps: std::collections::BTreeSet<String> =
            ["code-review", "lint-skill", "missing-pkg"].iter().map(|s| (*s).to_string()).collect();

        let result = validate_matches_manifest(&lf, &deps);
        assert!(result.is_err());
        let err_msg = format!("{}", result.err().unwrap());
        assert!(err_msg.contains("missing-pkg"));
    }

    #[test]
    fn validate_matches_manifest_empty_both() {
        let lf = Lockfile::new("aipm 0.10.0".to_string());
        let deps = std::collections::BTreeSet::new();

        assert!(validate_matches_manifest(&lf, &deps).is_ok());
    }

    #[test]
    fn validate_matches_manifest_extra_lockfile_ok() {
        // Lockfile may have transitive deps not in manifest — that's fine
        let lf = sample_lockfile();
        let deps: std::collections::BTreeSet<String> =
            ["code-review"].iter().map(|s| (*s).to_string()).collect();

        assert!(validate_matches_manifest(&lf, &deps).is_ok());
    }

    #[test]
    fn validate_matches_manifest_multiple_missing() {
        let lf = Lockfile::new("aipm 0.10.0".to_string());
        let deps: std::collections::BTreeSet<String> =
            ["dep-a", "dep-b"].iter().map(|s| (*s).to_string()).collect();

        let result = validate_matches_manifest(&lf, &deps);
        assert!(result.is_err());
        let err_msg = format!("{}", result.err().unwrap());
        assert!(err_msg.contains("dep-a"));
        assert!(err_msg.contains("dep-b"));
    }
}
